CREATE TABLE USERS_TBL(
USER_ID VARCHAR2(12) PRIMARY KEY,
FULL_NAME VARCHAR2(150) NOT NULL,
EMAIL VARCHAR2(120) NOT NULL,
MOBILE VARCHAR2(20),
ROLE VARCHAR2(20) NOT NULL,
PRIMARY_SKILL_OR_COMPANY VARCHAR2(150),
STATUS VARCHAR2(20)
);

CREATE TABLE PROJECT_TBL(
PROJECT_ID NUMBER(10) PRIMARY KEY,
CLIENT_USER_ID VARCHAR2(12) NOT NULL,
PROJECT_TITLE VARCHAR2(200) NOT NULL,
PROJECT_DESCRIPTION VARCHAR2(1000) NOT NULL,
BUDGET_MIN NUMBER(10,2) NOT NULL,
BUDGET_MAX NUMBER(10,2) NOT NULL,
POSTED_DATE DATE,
STATUS VARCHAR2(20),
AWARDED_BID_ID NUMBER(10),
CONSTRAINT FK_PROJECT_CLIENT FOREIGN KEY(CLIENT_USER_ID) REFERENCES USERS_TBL(USER_ID)
);

CREATE TABLE BID_TBL(
BID_ID NUMBER(10) PRIMARY KEY,
PROJECT_ID NUMBER(10) NOT NULL,
FREELANCER_USER_ID VARCHAR2(12) NOT NULL,
BID_AMOUNT NUMBER(10,2) NOT NULL,
DELIVERY_DAYS NUMBER(5) NOT NULL,
COVER_LETTER VARCHAR2(1000),
BID_DATE DATE,
BID_STATUS VARCHAR2(20),
CONSTRAINT FK_BID_PROJECT FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT_TBL(PROJECT_ID),
CONSTRAINT FK_BID_FREELANCER FOREIGN KEY(FREELANCER_USER_ID) REFERENCES USERS_TBL(USER_ID)
);

ALTER TABLE PROJECT_TBL ADD CONSTRAINT FK_PROJECT_AWARDED_BID FOREIGN KEY(AWARDED_BID_ID) REFERENCES BID_TBL(BID_ID);

INSERT INTO USERS_TBL(USER_ID,FULL_NAME,EMAIL,MOBILE,ROLE,PRIMARY_SKILL_OR_COMPANY,STATUS) VALUES('UCL1001','Rahul Mehta','rahul.mehta@company.com','9876500001','CLIENT','Mehta Digital Solutions','ACTIVE');
INSERT INTO USERS_TBL(USER_ID,FULL_NAME,EMAIL,MOBILE,ROLE,PRIMARY_SKILL_OR_COMPANY,STATUS) VALUES('UCL1002','Priya Sharma','priya.sharma@financecorp.com','9876500002','CLIENT','FinServe Pvt Ltd','ACTIVE');
INSERT INTO USERS_TBL(USER_ID,FULL_NAME,EMAIL,MOBILE,ROLE,PRIMARY_SKILL_OR_COMPANY,STATUS) VALUES('UFR2001','Arjun Nair','arjun.nair.dev@example.com','9876500003','FREELANCER','Full-Stack Java Developer','ACTIVE');
INSERT INTO USERS_TBL(USER_ID,FULL_NAME,EMAIL,MOBILE,ROLE,PRIMARY_SKILL_OR_COMPANY,STATUS) VALUES('UFR2002','Meera Iyer','meera.iyer.design@example.com','9876500004','FREELANCER','UI/UX Designer','INACTIVE');

INSERT INTO PROJECT_TBL(PROJECT_ID,CLIENT_USER_ID,PROJECT_TITLE,PROJECT_DESCRIPTION,BUDGET_MIN,BUDGET_MAX,POSTED_DATE,STATUS,AWARDED_BID_ID) VALUES(50001,'UCL1001','Build REST API for Inventory System','Develop REST APIs for inventory management using Java and JDBC.',20000.00,40000.00,DATE '2025-03-10','OPEN',NULL);
INSERT INTO PROJECT_TBL(PROJECT_ID,CLIENT_USER_ID,PROJECT_TITLE,PROJECT_DESCRIPTION,BUDGET_MIN,BUDGET_MAX,POSTED_DATE,STATUS,AWARDED_BID_ID) VALUES(50002,'UCL1002','Design Marketing Landing Page','Design a professional landing page for marketing campaign promotion.',8000.00,15000.00,DATE '2025-03-08','AWARDED',NULL);

INSERT INTO BID_TBL(BID_ID,PROJECT_ID,FREELANCER_USER_ID,BID_AMOUNT,DELIVERY_DAYS,COVER_LETTER,BID_DATE,BID_STATUS) VALUES(710001,50001,'UFR2001',25000.00,15,'I can build the inventory REST API with proper JDBC database operations.',DATE '2025-03-11','PENDING');
INSERT INTO BID_TBL(BID_ID,PROJECT_ID,FREELANCER_USER_ID,BID_AMOUNT,DELIVERY_DAYS,COVER_LETTER,BID_DATE,BID_STATUS) VALUES(710002,50002,'UFR2001',12000.00,7,'I can complete the marketing landing page with responsive design.',DATE '2025-03-09','ACCEPTED');
INSERT INTO BID_TBL(BID_ID,PROJECT_ID,FREELANCER_USER_ID,BID_AMOUNT,DELIVERY_DAYS,COVER_LETTER,BID_DATE,BID_STATUS) VALUES(710003,50002,'UFR2002',13000.00,10,'I can create a clean UI/UX design for the landing page.',DATE '2025-03-09','REJECTED');

UPDATE PROJECT_TBL SET AWARDED_BID_ID=710002 WHERE PROJECT_ID=50002;

COMMIT;